on:
  push:
    branches:
      - main

name: Release

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release Please
        id: release
        uses: GoogleCloudPlatform/release-please-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          package-name: cds
          changelog-types: >-
            [{"type": "feat", "section": "Features"},
             {"type": "fix", "section": "Bug Fixes"},
             {"type": "docs", "section": "Docs"},
             {"type": "refactor", "section": "Code Refactoring"},
             {"type": "perf", "section": "Performance"},
             {"type": "test", "section": "Tests"},
             {"type": "build", "section": "Build System"},
             {"type": "ci", "section":"CI"}]

  build-and-upload:
    name: Build & Upload cds binary
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nim
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: '2.2.4'

      - name: Build cds
        run: nim c -d:release -o:cds src/cds.nim

      - name: Upload binary to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: cds
